
exports.memes=[
    {
      cmd:'slap',
      id:438680,
      caplist:[true,true]
    },
  
  {
    cmd:'confuse',
    id:87743020,
    caplist:[false,false,true]
  },
    {
    cmd:'sharpturn',
    id:124822590,
    caplist:[false,false,false]
    },
    {
      cmd:'dexter',
      id:71428573,
      caplist:[true,true]
    },
    {
      cmd:'rockshock',
      id:21735,
      caplist:[false,false]
    },
    {
      cmd:'truth',
      id:123999232,
      caplist:[false,true]
    },
    {
      cmd:'shockpikachu',
      id:155067746,
      caplist:[false,false,false]
    },
    {
      cmd:'dudewithsign',
      id:216951317,
      caplist:[false,false]
    },
    {
      cmd:'makeup',
      id:195515965,
      caplist:[false,false,false,false]
    },
    {
      cmd:'drake',
      id:181913649,
      caplist:[false,false]
    },
    {
      cmd:'gorden',
      id:1894566,
      caplist:[true,true]
    },
    {
      cmd:'mind3',
      id:128933819,
      caplist:[true,true,true]
    },
    {
      cmd:'mind4',
      id:93895088,
      caplist:[true,true,true,true]
    }
  ];